languages:
    python: true
    javascrpt: true
exclude_paths:
- "papukaani/papukaaniApp/static/papukaani/js/leaflet.markercluster.js"
- "papukaani/papukaaniApp/static/papukaani/js/MarkerClusterGroup.Refresh.js"
- "papukaani/papukaaniApp/static/papukaani/libraries/*"
