languages:
    Python: true
    JavaScript: true
exclude_paths:
- "papukaaniApp/static/papukaani/js/leaflet.markercluster.js"
- "papukaaniApp/static/papukaani/js/MarkerClusterGroup.Refresh.js"
- "papukaaniApp/static/papukaani/libraries/*"

