import os
#Set the following enviroment variables:
#LAJISTORE_USER - developement/production username


LAJISTORE_USER = os.environ['LAJISTORE_USER']
LAJISTORE_PASSWORD = os.environ['LAJISTORE_PASSWORD']
LAJISTORE_TEST = os.environ["LAJISTORE_TEST"]
LAJISTORE_TEST_PASSWORD = os.environ['LAJISTORE_TEST_PASSWORD']
LAJISTORE_UNIT_TEST = os.environ["LAJISTORE_UNIT_TEST"]
LAJISTORE_UNIT_TEST_PASSWORD = os.environ['LAJISTORE_UNIT_TEST_PASSWORD']
TIPUAPI_USER = os.environ['TIPUAPI_USER']
TIPUAPI_PASSWORD = os.environ['TIPUAPI_PASSWORD']